### ISSUE TITLE
[sale_quotation_number] Error when duplicate sale quotation/sale order

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/sale-workflow#2]
https://github.com/OCA/sale-workflow/issues/303

Analytic acc:
1. sale_quotation_number - Natura Aromatik
2. sale_quotation_number - HTSI
3. sale_quotation_number - Inti Prima Rasa

**Comment by mikevhe18** [comment]
PR TO OCA [#304](https://github.com/OCA/sale-workflow/pull/304)
